language: python

python:
 - pypy3
 - 3.2
 - 3.3
 - 3.4

install:
 - sudo apt-get install mecab-ipadic-utf8 libmecab-dev
 - pip install coverage ftfy langcodes mecab-python3 msgpack-python regex

script:
 - coverage run --include=wordfreq/* -m nose -vx

after_success:
 - pip install coveralls
 - coveralls

after_script:
 - coverage report
 - pip install pep8 pyflakes
 - pep8 --statistics --count .
 - pyflakes . | tee >(wc -l)

matrix:
  fast_finish: true
